//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortfolioContent
    {
        public int PortfolioId { get; set; }
        public string PortfolioType { get; set; }
        public string PortfolioName { get; set; }
        public string PortfolioLogo { get; set; }
        public string PortfolioFrontLocation { get; set; }
        public string PortfolioLocation { get; set; }
        public string PortfolioServices { get; set; }
        public Nullable<System.DateTime> PortfolioDate { get; set; }
        public string PortfolioSite { get; set; }
        public string PortfolioDetails { get; set; }
        public int PortfolioOrder { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public bool isDeleted { get; set; }
    }
}
